services:
  cdmamba:
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ..:/app
      - /data:/app/data
    command: --config /app/configs/cdmamba-config.yaml
    runtime: nvidia




