services:
  cdmamba:
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHEBUST: ${CACHEBUST:-1}   # default 1, can be overridden
    volumes:
      - /data:/app/data
      - /opt/configs:/app/configs
    command: --config /app/configs/config.yaml
#    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]




