services:
  cdmamba:
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - /data:/app/data
      - /opt/configs:/app/configs
    command: --config /app/configs/config.yaml
    runtime: nvidia




